#!/bin/sh
# pack into a tar.gz with a particular version number
# the form package-version.tar.gz is expected by an rpm packager

package=jed
version=0.99.19

[ "$#" -gt 0 ] && version=$1

echo "create $package-$version.tar.gz"

tar -cvzf \
    $package-$version.tar.gz \
    --transform="s:^$package:$package-$version:" \
    $package/*

